version: '3.1'

services:
  api-digital-wallet:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: api-digital-wallet
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
      - ./logs/apache2:/var/log/apache2
    depends_on:
      - database
    links:
      - database
    networks:
      - api-connection
    env_file:
      - .env

  database:
    container_name: bd-api-digital-wallet
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
    networks:
      - api-connection

networks:
  api-connection:
    name: api-connection-network