version: '3.1'

services:
  apache:
    image: php:8.0.2-apache
    container_name: api-digital-wallet
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    links:
      - database

  database:
    container_name: bd-api-digital-wallet
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: digital-wallet
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin