apiVersion: apps/v1
kind: Deployment
metadata:
  name: digital-wallet
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: digital-wallet
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: env-configmap
      initContainers:
        - name: {{ .Release.Name }}-migration
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          command: ["php", "./db/script_release_1.php"]
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: env-configmap