apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cron-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Release.Name }}-cron-job
              image: rafaelo19/api-digital-wallet:{{ .Values.image.tag }}
              command: ["/usr/local/bin/php", "/var/www/html/SendQueues.php"]
              envFrom:
                - configMapRef:
                    name: env-configmap
          restartPolicy: OnFailure