apiVersion: apps/v1
kind: Deployment
metadata:
  name: digital-wallet
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: digital-wallet
          image: rafaelo19/api-digital-wallet:{{ .Values.image.tag }}
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: env-configmap