apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: {{ .Values.database.replicas }}
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: {{ .Values.database.name }}
          image: {{ .Values.database.image }}:{{ .Values.database.tag }}
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: {{ .Values.database.port }}
          envFrom:
            - configMapRef:
                name: postgres-configmap