expose_php = Off
display_errors = Off
log_errors = On
error_reporting = E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED
memory_limit = 256M
max_execution_time = 30
max_input_time = 60
zend.exception_ignore_args = On
date.timezone = UTC
opcache.enable = 1
opcache.validate_timestamps = 1
